# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Survey Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Survey Project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

pod 'Starscream', '~> 3.0.2'
pod "SearchTextField"

end
